pluginManagement {
    repositories {
        gradlePluginPortal()
        // ForgeGradle 6
        maven { url = 'https://maven.minecraftforge.net/' }
        // Parchment / Librarian
        maven { url = 'https://maven.parchmentmc.org' }
        // MixinGradle
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
